version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 8
    ignore:
      - dependency-name: "debug"
        versions: ["<4.3.1"]
    commit-message:
      prefix: "deps"
      prefix-development: "chore"
      include: scope
    labels:
      - "dependencies"
      - "dependabot"
    rebase-strategy: "auto"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    commit-message:
      prefix: "dependabot"
      include: scope
